<a href="https://colab.research.google.com/github/jonathanahc/Practicas/blob/main/Pr%C3%A1ctica_4_Manipulaci%C3%B3n_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import numpy as np

Mounted at /content/drive


**Crea dos matrices de 3x3 con números aleatorios entre 1 y 10**

In [2]:
matriz1 = np.array(np.random.randint(1,10, size=(3,3)))
print(matriz1)

print("\n")

matriz2 = np.array(np.random.randint(1,10, size=(3,3)))
print(matriz2)

[[9 2 9]
 [4 5 1]
 [6 6 4]]


[[5 9 7]
 [7 7 7]
 [6 9 1]]


**Suma ambas matrices**

In [3]:
suma = matriz1 + matriz2
print(suma)

[[14 11 16]
 [11 12  8]
 [12 15  5]]


**Resta la segunda matriz de la primera**

In [4]:
resta = matriz2 - matriz1
print(resta)

[[-4  7 -2]
 [ 3  2  6]
 [ 0  3 -3]]


**Multiplica la primera matriz por 2**

In [5]:
multiplicacion = np.multiply(matriz1, 2)
print(multiplicacion)

[[18  4 18]
 [ 8 10  2]
 [12 12  8]]


**Realiza una multiplicación matricial entre las dos matrices**

In [8]:
multiplicacion = np.dot(matriz1, matriz2)
print(multiplicacion)

[[113 176  86]
 [ 61  80  64]
 [ 96 132  88]]
