<a href="https://colab.research.google.com/github/jonathanahc/Practicas/blob/main/Pr%C3%A1ctica_4_Manipulaci%C3%B3n_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import numpy as np

Mounted at /content/drive


In [3]:
# Crea dos matrices de 3x3 con números aleatorios entre 1 y 10

matriz1 = np.array(np.random.randint(1,10, size=(3,3)))
print(matriz1)

print("\n")

matriz2 = np.array(np.random.randint(1,10, size=(3,3)))
print(matriz2)

[[7 6 6]
 [1 9 9]
 [3 8 8]]


[[3 6 2]
 [9 7 3]
 [5 5 6]]


In [4]:
# 1. Suma ambas matrices

suma = matriz1 + matriz2
print(suma)

[[10 12  8]
 [10 16 12]
 [ 8 13 14]]


In [5]:
# 2. Resta la segunda matriz de la primera

resta = matriz2 - matriz1
print(resta)

[[-4  0 -4]
 [ 8 -2 -6]
 [ 2 -3 -2]]


In [6]:
# 3. Multiplica la primera matriz por 2

multiplicacion = matriz1 * 2
print(multiplicacion)

[[14 12 12]
 [ 2 18 18]
 [ 6 16 16]]


In [7]:
# 4. Realiza una multiplicación matricial entre las dos matrices

multiplicacion = matriz1 * matriz2
print(multiplicacion)

[[21 36 12]
 [ 9 63 27]
 [15 40 48]]
